name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js '22.x'
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install Dependencies
        run: npm install

      - name: Build with tsup
        run: npm run build

      - name: Package Binaries
        run: npm run pkg .

      - name: Print Directory Structure
        run: ls -R
        shell: bash

      - name: Run npm Audit
        run: npm audit signatures

      - name: Release on GitHub & Publish to NPM
        if: github.ref_name == 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Upload Built Binaries to GitHub Release
        if: github.ref_name == 'main'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            brew/snackmoney-linux
            brew/snackmoney-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
